---
version: "2"
services:
  frontend:
    build:
      context: ./
    container_name: lms
    restart: always
    ports:
      - 7010:3000
    depends_on:
      - db
      - prisma-studio
    links:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  prisma-studio:
    links:
      - db
    depends_on:
      - db
    build:
      context: ./docker/prismaStudio
      dockerfile: Dockerfile
    container_name: prisma-studio
    restart: unless-stopped
    ports:
      - "5555:5555"
    volumes:
      - ./prisma:/app/prisma


  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=lms
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local
